
CREATE TABLE PRODUCT(
    code varchar(40) not  null,
    name varchar(40) not null,
    price integer not null,
    primary key(code)
);

CREATE TABLE SALE_HISTORY(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    sale_person VARCHAR(40) NOT NULL,
    sale_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE SALE_PRODUCT (
    code varchar(40) not null,
    sale_id varchar(40) not null,
    unit_price integer not null,
    quantity integer not null,
    primary key (code,sale_id),
    foreign key (code) references PRODUCT (code),
    foreign key(sale_id) references SALE_HISTORY (id)
);